<a href="https://colab.research.google.com/github/Light-coder777/Gojo_Wallpaper/blob/master/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import statistics as st
import scipy as stats

In [6]:
#1. Find arithmetic mean of 20, 2, 7, 1, 34
A = [20,2,7,1,34]
print("Arthmetic Mean of Array: " + str(np.mean(A)))
A1 = np.array([20,2,7,1,34])
print(np.mean(A1))
print(st.mean(A1))

Arthmetic Mean of Array: 12.8
12.8
12


In [14]:
# 2. Create following matrix using multidimensional array and calculate arithmetic mean for each column, each row and considering entire data.
# 14 17 12 33 44  
# 15  6 27  8 19 
# 23  2 54  1 4 
B = np.array([[14,17,12,33,44],[15,6,27,8,19],[23,2,54,1,4]])
print(B)
print("Columnwise representation of the Mean of the row: " + str(np.mean(B, axis = 0)))
print("Rowwise representation of the Mean of the row: " + str(np.mean(B, axis = 1)))
print(np.mean(B))


[[14 17 12 33 44]
 [15  6 27  8 19]
 [23  2 54  1  4]]
Columnwise representation of the Mean of the row: [17.33333333  8.33333333 31.         14.         22.33333333]
Rowwise representation of the Mean of the row: [24.  15.  16.8]
18.6


In [20]:
# 3. Find minimum value, maximum value and range for entire data, column wise and row wise.
# 3,7,5
# 8,4,3
# 2,4,9
C = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(C)
print(np.min(C))
print(np.min(C,axis = 0))
print(np.min(C,axis = 1))
print(np.max(C))
print(np.max(C,axis = 0))
print(np.max(C,axis = 1))

[[3 7 5]
 [8 4 3]
 [2 4 9]]
2
[2 4 3]
[3 3 2]
9
[8 7 9]
[7 8 9]


In [ ]:
# 4. Find weighted average for the data given below.
# Outcomes	Frequency
# 1	4
# 2	3
# 3	2
# 4	1
X = np.array([1,2,3,4])
W = np.array([4,3,2,1])
print("The Weighted Average of the given Data = " + str(np.average(X, weights=)) )

In [28]:
# 5. The speed of 13 vehicles is 99,86,87,88,111,86,103,87,94,78,77,85,86
# Find mean, median and mode.

Speed = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])
print("Arithematic Mean of the Speed: "+ str(np.mean(Speed)))
print("Median of the Speed: " + str(np.median(Speed)))
from scipy import stats
print("Mode of Speeds" + str(stats.mode(Speed)))

Arithematic Mean of the Speed: 89.76923076923077
Median of the Speed: 87.0
Mode of SpeedsModeResult(mode=array([86]), count=array([3]))


In [32]:
# 6. Calculate geometric mean for each column, each row and considering entire data.
# 1 3 27
# 3 4 6
# 7 6 3
# 3 6 8
from scipy.stats.mstats import gmean
M = np.array([[1,3,27],[3,4,6],[7,6,3],[3,6,8]])
print("Geometric Mean of the entire matrix M = " + str(gmean(gmean(M))))
print("Geometric Mean of the entire Column matrix M = " + str(gmean(gmean(M, axis = 0))))
print("Geometric Mean of the entire Row matrix M = " + str(gmean(gmean(M, axis = 1))))

Geometric Mean of the entire matrix M = 4.663506066439651
Geometric Mean of the entire Column matrix M = 4.663506066439651
Geometric Mean of the entire Row matrix M = 4.663506066439651


In [33]:
# 7. Calculate harmonic mean for 1, 3, 5, 7, 9
from scipy.stats.mstats import hmean
H = np.array([1, 3, 5, 7, 9])
print("Harmonic Mean is "+ str(hmean(H)))

Harmonic Mean is 2.797513321492007


In [ ]:
# 8. Calculate median for each column, each row and considering entire data.
# 30 65 70
# 80 95 10
# 50 90 60


In [35]:
# 9. Its way too big____
A = np.array([[0,0.99,2,0],[1,1.99,4,0],[2,2.99,6,0],[3,3.99,7,0]])
print(np.__version__)
print(F)
print("Mean of the entire Matrix A: " + str(np.median(A)))
print("Columnwise Mean of the entire Matrix A: " + str(np.median(A, axis= 0)))
print("Rowwise Mean of the entire Matrix A: " + str(np.median(A, axis = 1)))

1.19.5


In [42]:
def grouped_mean(A):
  n = len(A)
  Sum = 0
  F = 0
  for i in range(n):
    Sum = Sum + ((A[i][0] + A[i][1])/2)*A[i][2]
    F = F + A[i][2]
  Mean = Sum/F
  return Mean

def grouped_median(A):
  n=len(A)
  N=0
  for i in range(n):
    N=N+A[i][2]
    if i==0:
      A[i][3]=A[i][2]
    else:
      A[i][3]=A[i][2]+A[i-1][3]
  m=A[i][3]/2
  for i in range(n-1):
    if A[i][3]< m <=A[i+1][3]:
      print("Median Class is "+str(A[i+1][0])+"-"+str(A[i+1][1]))
      L=A[i+1][0]
      IW=A[i+1][1]-A[i+1][0]
      CF=A[i][3]
      F=A[i+1][2]
      Median= L+(m-CF)*IW/F
      break;
  return Median

print(grouped_mean(A))
print(grouped_median(A))

2.4423684210526315
Median Class is 2.0-2.99
2.5775
